### ISSUE TITLE
Fallo en el ultimo boton

### ISSUE THREAD

**Issue by gaal1le0** [jesus-cano-ortega/random-card-generator#1]
Cuando se acaba de repetir las 52 combinaciones debería aparecer una alerta indicándomelos y el programa debería ejercutarse desde cero para poder volver a repetir las 52 combinaciones.

**Comment by jesus-cano-ortega** [comment]
Fallo del último botón corregido. Te dejo por aquí el [commit](https://github.com/jesus-cano-ortega/random-card-generator/commit/a101f45764af1789c2d675b23d595a7811a8ab8d) realizado.
